
#ifdef _KERNEL_MODE
#include <ntifs.h>
#else
#include <Windows.h>
#endif

typedef struct _IO_REQUEST_PROCESS_HANDLE
{
	ULONG_PTR ProcessId;
	ULONG_PTR ClientDLL;
} IO_REQUEST_PROCESS_HANDLE, *PIO_REQUEST_PROCESS_HANDLE;

typedef struct _IO_REQUEST_READ_MEMORY
{
	ULONG_PTR ProcessId;
	ULONG_PTR AddressFrom;
	PVOID Buffer;
	SIZE_T ReadSize;
} IO_REQUEST_READ_MEMORY, *PIO_REQUEST_READ_MEMORY;

typedef struct _IO_REQUEST_WRITE_MEMORY
{
	ULONG_PTR ProcessId;
	ULONG_PTR AddressTo;
	PVOID Buffer;
	SIZE_T WriteSize;
} IO_REQUEST_WRITE_MEMORY, * PIO_REQUEST_WRITE_MEMORY;

#define IO_CTL_GETPROCESSHANDLE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_CTL_READMEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_CTL_WRITEMEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
